import { Injectable, signal, effect } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class LanguageService {
  // Default to Arabic
  currentLang = signal<'ar' | 'en'>(this.getSavedLang() || 'ar');

  translations: any = {
    ar: {
      nav: {
        home: 'الرئيسية',
        newArrivals: 'وصلنا حديثاً',
        categories: 'الفئات',
        offers: 'العروض',
        login: 'تسجيل الدخول',
        signup: 'إنشاء حساب',
        logout: 'تسجيل الخروج',
        addresses: 'عناويني',
        cart: 'السلة',
        orders: 'طلباتي',
        wishlist: 'المفضلة'
      },
      orders: {
        title: 'طلباتي',
        details: 'تفاصيل الطلب',
        orderId: 'رقم الطلب',
        items: 'المنتجات',
        emptyTitle: 'لا توجد طلبات بعد',
        emptyDesc: 'لم تقم بإجراء أي طلبات حتى الآن. ابدأ التسوق الآن!',
        backToList: 'العودة لقائمة طلباتي'
      },
      cart: {
        title: 'سلة المشتريات',
        addSuccess: 'تمت إضافة المنتج إلى السلة بنجاح',
        removeError: 'فشل في إزالة المنتج',
        selectAddress: 'يرجى اختيار عنوان التوصيل',
        checkoutSuccess: 'تم إرسال الطلب بنجاح!',
        checkoutError: 'فشل في إتمام الطلب',
        qty: 'الكمية:',
        summary: 'ملخص الطلب',
        subtotal: 'المجموع الفرعي',
        shipping: 'الشحن',
        free: 'مجاني',
        total: 'الإجمالي',
        deliveryAddress: 'عنوان التوصيل',
        noAddress: 'يرجى إضافة عنوان توصيل أولاً.',
        addAddress: 'إضافة عنوان',
        checkout: 'إتمام الطلب',
        emptyTitle: 'سلتك فارغة',
        emptyDesc: 'يبدو أنك لم تقم بإضافة أي منتجات إلى سلتك بعد.',
        continue: 'مواصلة التسوق'
      },
      addresses: {
        title: 'عناويني',
        desc: 'إدارة عناوين التوصيل الخاصة بك.',
        addNew: 'إضافة عنوان جديد',
        loadError: 'فشل في تحميل العناوين',
        updateSuccess: 'تم تحديث العنوان بنجاح',
        updateError: 'فشل في تحديث العنوان',
        addSuccess: 'تمت إضافة العنوان بنجاح',
        addError: 'فشل في إضافة العنوان',
        deleteSuccess: 'تم حذف العنوان بنجاح',
        deleteError: 'فشل في حذف العنوان',
        defaultSuccess: 'تم تعيين العنوان الافتراضي',
        defaultError: 'فشل في تعيين العنوان الافتراضي',
        setAsDefault: 'تعيين كافتراضي',
        default: 'الافتراضي',
        emptyTitle: 'لا توجد عناوين',
        emptyDesc: 'لم تقم بإضافة أي عناوين للتوصيل بعد.',
        editTitle: 'تعديل العنوان',
        addTitle: 'إضافة عنوان',
        city: 'المدينة',
        cityPlaceholder: 'مثال: الرياض',
        street: 'الشارع والتفاصيل',
        streetPlaceholder: 'مثال: طريق الملك فهد، مبنى 12',
        save: 'حفظ التغييرات',
        create: 'إضافة العنوان'
      },
      footer: {
        privacy: 'سياسة الخصوصية',
        terms: 'الشروط والأحكام',
        shipping: 'سياسة الشحن'
      },
      hero: {
        badge: '🚀 مجموعة صيف 2026 الجديدة',
        title: 'أعد تعريف <span class="text-indigo-600">أناقتك</span> مع متجر الأولاد الثمانية.',
        desc: 'اكتشف مجموعة مختارة من الملابس والإكسسوارات الفاخرة المصممة للفرد العصري. الجودة تلتقي بالراحة في كل غرزة.',
        shopNow: 'تسوق الآن',
        viewCatalog: 'عرض الكتالوج',
        trustedBy: 'موثوق من قبل'
      },
      home: {
        storeName: 'متجر الأولاد الثمانية',
        featuredItem: 'قطعة مميزة',
        coatName: 'معطف الصوف الليلي',
        collections: 'مجموعات مختارة',
        collectionsDesc: 'استكشف الفئات الأكثر شهرة لدينا هذا الموسم.',
        viewAll: 'عرض الكل',
        footwear: 'أحذية',
        accessories: 'إكسسوارات',
        streetwear: 'ملابس عصرية',
        items: 'قطعة',
        newsletterTitle: 'انضم إلى دائرتنا الخاصة',
        newsletterDesc: 'احصل على وصول حصري لأحدث الصيحات، المبيعات الخاصة، ونصائح الموضة مباشرة إلى بريدك الإلكتروني.',
        subscribe: 'اشترك الآن',
        emailPlaceholder: 'أدخل بريدك الإلكتروني',
        rights: 'جميع الحقوق محفوظة.'
      },
      login: {
        title: 'مرحباً بعودتك',
        subtitle: 'أدخل بياناتك للوصول إلى حسابك',
        email: 'البريد الإلكتروني',
        password: 'كلمة المرور',
        rememberMe: 'تذكرني',
        forgotPass: 'نسيت كلمة المرور؟',
        submit: 'تسجيل الدخول',
        noAccount: 'ليس لديك حساب؟',
        createAccount: 'إنشاء حساب جديد'
      },
      register: {
        title: 'إنشاء حساب',
        subtitle: 'انضم إلى 8Boys وابدأ رحلة التسوق الخاصة بك',
        fullName: 'الاسم الكامل',
        username: 'اسم المستخدم',
        email: 'البريد الإلكتروني',
        phone: 'رقم الهاتف',
        password: 'كلمة المرور',
        passHint: 'يجب أن تتكون من 6 أحرف على الأقل مع أرقام وحروف.',
        agree: 'بإنشاء حساب، فإنك توافق على <a href="#" class="text-indigo-600 font-semibold underline">شروط الخدمة</a> و <a href="#" class="text-indigo-600 font-semibold underline">سياسة الخصوصية</a>.',
        submit: 'إنشاء حساب',
        hasAccount: 'لديك حساب بالفعل؟',
        signIn: 'سجل دخولك هنا'
      },
      admin: {
        dashboard: {
          title: 'لوحة التحكم'
        },
        nav: {
          products: 'المنتجات',
          categories: 'الفئات',
          colors: 'الألوان',
          badges: 'الأوسمة',
          orders: 'الطلبات'
        },
        sidebar: {
          products: 'إدارة المنتجات',
          categories: 'إدارة الـتصنيفات',
          colors: 'إدارة الألوان',
          badges: 'إدارة الأوسمة',
          orders: 'إدارة الطلبات',
          analysis: 'تحليل الأداء',
          status: 'حالة النظام',
          encrypted: 'اتصال مشفر',
          logout: 'تسجيل الخروج'
        },
        header: {
          protocol: 'بروتوكول المدير',
          welcome: 'مرحبا، المدير',
          desc: 'إدارة المتجر والمزامنة في الوقت الفعلي.',
          catalog: 'كتالوج المنتجات',
          hierarchy: 'هيكل الفئات',
          palette: 'لوحة الألوان',
          stamps: 'نظام الأوسمة',
          access: 'صلاحية المستوى 4',
          online: 'متصل',
          control: 'لوحة تحكم',
          addProduct: 'منتج جديد',
          newCategory: 'فئة جديدة',
          defineColor: 'تعريف لون',
          createBadge: 'إنشاء وسم',
          identity: 'الهوية',
          category: 'الفئة',
          price: 'السعر',
          stock: 'المخزون',
          actions: 'الإجراءات',
          units: 'قطعة',
          depleted: 'نفد',
          activeStamp: 'وسم نشط',
          destroy: 'حذف',
          sub: 'فرعي من',
          ordersTitle: 'وحدة الطلبات قيد الإنشاء',
          ordersDesc: 'سيتوفر تتبع الطلبات ومعالجتها في التحديث القادم.',
          addUnit: 'إضافة وحدة جديدة',
          createCategory: 'إنشاء فئة',
          addColor: 'إضافة لون',
          addBadge: 'إضافة وسم',
          adminPanel: 'لوحة التحكم الإدارية',
          unitName: 'اسم الوحدة',
          description: 'الوصف',
          selectCategory: 'اختر فئة',
          serialCode: 'الرمز التسلسلي',
          colorOption: 'خيار اللون',
          customNoColor: 'مخصص / بدون لون',
          badgeSticker: 'وسم (ملصق)',
          noBadge: 'بدون وسم',
          newColorName: 'اسم لون جديد',
          newHexCode: 'كود لون جديد',
          sizeSpec: 'الحجم / المواصفات',
          initialStock: 'المخزون الأولي',
          cost: 'التكلفة',
          sale: 'سعر البيع',
          disc: 'خصم%',
          unitImages: 'صور الوحدة',
          processing: 'جارٍ المعالجة...',
          deployUnit: 'نشر الوحدة',
          categoryName: 'اسم الفئة',
          parentCategory: 'الفئة الأساسية (اختياري)',
          mainCategory: 'فئة رئيسية',
          hexCode: 'كود اللون',
          colorName: 'اسم اللون',
          badgeName: 'اسم الوسم',
          cancel: 'إلغاء',
          confirm: 'تأكيد',
          confirmOp: 'تأكيد العملية',
          add: 'إضافة',
          editProduct: 'تعديل المنتج',
          updateProduct: 'تحديث المنتج'
        },
        stats: {
          products: 'إجمالي المنتجات',
          orders: 'إجمالي الطلبات',
          revenue: 'الأرباح',
          customers: 'العملاء'
        },
        products: {
          title: 'كتالوج المنتجات',
          sync: 'مزامنة قاعدة البيانات نشطة',
          unit: 'تفاصيل الوحدة',
          category: 'المجموعة',
          valuation: 'التقييم',
          inventory: 'حالة المخزون',
          operations: 'العمليات',
          deploy: 'إرسال للمتجر',
          new: 'منتج جديد',
          name: 'اسم المنتج',
          badge: 'الوسم',
          price: 'السعر',
          stock: 'المخزون الأولي',
          img: 'رابط الصورة',
          desc: 'الوصف',
          add: 'إضافة منتج'
        },
        categories: {
          title: 'هيكل الفئات',
          sync: 'تخطيط هيكلي للفئات العالمية',
          new: 'فئة جديدة',
          name: 'اسم الفئة',
          parent: 'الفئة الأب (اختياري)',
          none: 'أساسي (رئيسي)',
          childOf: 'فرعي من: ',
          root: 'مستوى أساسي',
          sub: 'مستوى فرعي',
          map: 'ربط الفئة'
        },
        colors: {
          title: 'إدارة الألوان',
          new: 'لون جديد',
          name: 'اسم اللون',
          hex: 'كود اللون (HEX)',
          preview: 'معاينة',
          add: 'إضافة اللون'
        },
        badges: {
          title: 'إدارة الأوسمة',
          new: 'وسم جديد',
          name: 'اسم الوسم',
          add: 'إضافة الوسم'
        }
      },
      productDetail: {
        back: 'العودة للمتجر',
        backAdmin: 'العودة للوحة التحكم',
        loading: 'جارٍ التحميل...',
        selectOption: 'اختر خياراً',
        variants: 'المتغيرات',
        addVariant: 'إضافة متغير',
        description: 'الوصف',
        noDescription: 'لا يوجد وصف متاح.',
        stock: 'المخزون',
        code: 'الرمز',
        category: 'الفئة',
        price: 'السعر',
        off: '% خصم',
        save: 'وفّر',
        units: 'قطعة',
        outOfStock: 'نفد',
        addToCart: 'أضف إلى السلة',
        general: 'عام',
        notFound: 'المنتج غير موجود',
        notFoundDesc: 'المنتج الذي تبحث عنه غير متوفر أو تم نقله.',
        goBack: 'العودة',
        default: 'افتراضي',
        soldOut: 'نفد من المخزون',
        addVariantTitle: 'إضافة متغير جديد',
        configureStock: 'تكوين المخزون لـ',
        size: 'الحجم / المقاس',
        sizePlaceholder: 'مثال: XL، 42، 50ml',
        internalCode: 'الرمز الداخلي',
        inventoryStock: 'كمية المخزون',
        existingColor: 'لون موجود',
        selectColor: 'اختر لوناً (اختياري)',
        newColorName: 'أو اسم لون جديد',
        newColorHex: 'كود اللون الجديد',
        realPrice: 'سعر التكلفة',
        salePrice: 'سعر البيع',
        discount: 'الخصم %',
        variantImages: 'صور المتغير (تحميل متعدد)',
        deploying: 'جارٍ الحفظ...',
        deployVariant: 'حفظ المتغير',
        cancel: 'إلغاء',
        delete: 'حذف',
        confirmDelete: 'هل أنت متأكد؟',
        deleteVariantMsg: 'سيتم حذف هذا المتغير نهائياً ولا يمكن التراجع.',
      },
      wishlist: {
        title: 'منتجاتك المفضلة',
        subtitle: 'المنتجات التي قمت بحفظها لوقت لاحق.',
        empty: 'قائمة المفضلة فارغة',
        emptyDesc: 'استكشف مجموعتنا وأضف المنتجات التي تعجبك إلى مفضلتك.',
        explore: 'ابدأ التسوق',
        removed: 'تمت الإزالة من المفضلة',
        error: 'فشلت العملية',
        view: 'عرض المنتج'
      }
    },
    en: {
      nav: {
        home: 'Home',
        newArrivals: 'New Arrivals',
        categories: 'Categories',
        offers: 'Offers',
        login: 'Login',
        signup: 'Sign Up',
        logout: 'Logout',
        addresses: 'My Addresses',
        cart: 'Cart',
        orders: 'My Orders',
        wishlist: 'Wishlist'
      },
      orders: {
        title: 'My Orders',
        details: 'Order Details',
        orderId: 'Order ID',
        items: 'Order Items',
        emptyTitle: 'No Orders Yet',
        emptyDesc: 'You haven\'t placed any orders yet. Start shopping now!',
        backToList: 'Back to My Orders'
      },
      cart: {
        title: 'Shopping Cart',
        addSuccess: 'Product added to cart successfully',
        removeError: 'Failed to remove item',
        selectAddress: 'Please select a delivery address',
        checkoutSuccess: 'Order placed successfully!',
        checkoutError: 'Failed to place order',
        qty: 'Qty:',
        summary: 'Order Summary',
        subtotal: 'Subtotal',
        shipping: 'Shipping',
        free: 'Free',
        total: 'Total',
        deliveryAddress: 'Delivery Address',
        noAddress: 'Please add a delivery address first.',
        addAddress: 'Add Address',
        checkout: 'Place Order',
        emptyTitle: 'Your Cart is Empty',
        emptyDesc: 'Looks like you haven\'t added any items to your cart yet.',
        continue: 'Continue Shopping'
      },
      addresses: {
        title: 'My Addresses',
        desc: 'Manage your delivery addresses.',
        addNew: 'Add New Address',
        loadError: 'Failed to load addresses',
        updateSuccess: 'Address updated successfully',
        updateError: 'Failed to update address',
        addSuccess: 'Address added successfully',
        addError: 'Failed to add address',
        deleteSuccess: 'Address deleted successfully',
        deleteError: 'Failed to delete address',
        defaultSuccess: 'Default address set',
        defaultError: 'Failed to set default address',
        setAsDefault: 'Set as Default',
        default: 'Default',
        emptyTitle: 'No Addresses Found',
        emptyDesc: 'You haven\'t added any delivery addresses yet.',
        editTitle: 'Edit Address',
        addTitle: 'Add Address',
        city: 'City',
        cityPlaceholder: 'e.g. Riyadh',
        street: 'Street & Details',
        streetPlaceholder: 'e.g. King Fahad Road, Building 12',
        save: 'Save Changes',
        create: 'Create Address'
      },
      footer: {
        privacy: 'Privacy',
        terms: 'Terms',
        shipping: 'Shipping'
      },
      hero: {
        badge: '🚀 New Summer Collection 2026',
        title: 'Redefine Your <span class="text-indigo-600">Style</span> with 8Boys.',
        desc: 'Discover a curated selection of premium apparel and accessories designed for the modern individual. Quality meets comfort in every stitch.',
        shopNow: 'Shop Now',
        viewCatalog: 'View Catalog',
        trustedBy: 'Trusted By'
      },
      home: {
        storeName: '8Boys Shop',
        featuredItem: 'Featured Item',
        coatName: 'Midnight Wool Coat',
        collections: 'Featured Collections',
        collectionsDesc: 'Explore our most popular categories this season.',
        viewAll: 'View all',
        footwear: 'Footwear',
        accessories: 'Accessories',
        streetwear: 'Streetwear',
        items: 'Items',
        newsletterTitle: 'Join the Inner Circle',
        newsletterDesc: 'Get exclusive access to new arrivals, private sales, and fashion tips delivered straight to your inbox.',
        subscribe: 'Subscribe',
        emailPlaceholder: 'Enter your email',
        rights: '8Boys Ecommerce. All rights reserved.'
      },
      login: {
        title: 'Welcome Back',
        subtitle: 'Enter your credentials to access your account',
        email: 'Email Address',
        password: 'Password',
        rememberMe: 'Remember me',
        forgotPass: 'Forgot Password?',
        submit: 'Sign In',
        noAccount: "Don't have an account?",
        createAccount: 'Create account'
      },
      register: {
        title: 'Create Account',
        subtitle: 'Join 8Boys and start your shopping journey',
        fullName: 'Full Name',
        username: 'Username',
        email: 'Email Address',
        phone: 'Phone Number',
        password: 'Password',
        passHint: 'Must be at least 6 characters with letters and numbers.',
        agree: 'By creating an account, you agree to our <a href="#" class="text-indigo-600 font-semibold underline">Terms of Service</a> and <a href="#" class="text-indigo-600 font-semibold underline">Privacy Policy</a>.',
        submit: 'Create Account',
        hasAccount: 'Already have an account?',
        signIn: 'Sign in here'
      },
      admin: {
        dashboard: {
          title: 'Dashboard'
        },
        nav: {
          products: 'Products',
          categories: 'Categories',
          colors: 'Colors',
          badges: 'Badges',
          orders: 'Orders'
        },
        sidebar: {
          products: 'Manage Products',
          categories: 'Manage Categories',
          colors: 'Manage Colors',
          badges: 'Manage Badges',
          orders: 'Manage Orders',
          analysis: 'Performance Analysis',
          status: 'Node Status',
          encrypted: 'Encrypted Connection',
          logout: 'Terminal Logout'
        },
        header: {
          protocol: 'Admin Protocol',
          welcome: 'Welcome, Manager',
          desc: 'Real-time store management and synchronization.',
          catalog: 'Catalog Grid',
          hierarchy: 'Hierarchy Tree',
          palette: 'Color Palette',
          stamps: 'Badge System',
          access: 'Level 4 Access',
          online: 'Online',
          control: 'Control',
          addProduct: 'New Product',
          newCategory: 'New Category',
          defineColor: 'Define Color',
          createBadge: 'Create Badge',
          identity: 'Identity',
          category: 'Category',
          price: 'Price',
          stock: 'Stock',
          actions: 'Actions',
          units: 'Units',
          depleted: 'Depleted',
          activeStamp: 'Active Stamp',
          destroy: 'Destroy',
          sub: 'Sub',
          ordersTitle: 'Orders Module Under Construction',
          ordersDesc: 'Real-time order tracking and fulfillment will be available in the next update.',
          addUnit: 'Add New Unit',
          createCategory: 'Create Category',
          addColor: 'Define Color',
          addBadge: 'Create Badge',
          adminPanel: 'Administrative Control Panel',
          unitName: 'Unit Name',
          description: 'Description',
          selectCategory: 'Select Category',
          serialCode: 'Serial Code',
          colorOption: 'Color Option',
          customNoColor: 'Custom / No Color',
          badgeSticker: 'Badge (Sticker)',
          noBadge: 'No Badge',
          newColorName: 'New Color Name',
          newHexCode: 'New Hex Code',
          sizeSpec: 'Size / Spec',
          initialStock: 'Initial Stock',
          cost: 'Cost',
          sale: 'Sale',
          disc: 'Disc%',
          unitImages: 'Unit Images',
          processing: 'Processing...',
          deployUnit: 'Deploy Unit',
          categoryName: 'Category Name',
          parentCategory: 'Parent Category (Optional)',
          mainCategory: 'Main Category',
          hexCode: 'Hex Code',
          colorName: 'Color Name',
          badgeName: 'Badge Name',
          cancel: 'Cancel',
          confirm: 'Confirm',
          confirmOp: 'Confirm Operation',
          add: 'Add',
          editProduct: 'Edit Product',
          updateProduct: 'Update Product'
        },
        stats: {
          products: 'Total Products',
          orders: 'Total Orders',
          revenue: 'Revenue',
          customers: 'Customers'
        },
        products: {
          title: 'Product Catalog',
          sync: 'Live database synchronization active',
          unit: 'Unit Details',
          category: 'Collection',
          valuation: 'Valuation',
          inventory: 'Inventory Status',
          operations: 'Operations',
          deploy: 'Deploy to Store',
          new: 'New Product',
          name: 'Product Designation',
          badge: 'Product Badge',
          price: 'Price (USD)',
          stock: 'Initial Stock',
          img: 'Media Assets (URL)',
          desc: 'Description',
          add: 'Add Product'
        },
        categories: {
          title: 'System Hierarchy',
          sync: 'Structural mapping of global categories',
          new: 'New Category',
          name: 'Identifier Name',
          parent: 'Parent Entity Mapping',
          none: 'None (Primary)',
          childOf: 'Child of: ',
          root: 'Root Level',
          sub: 'Sub Level',
          map: 'Map Category'
        },
        colors: {
          title: 'Color Management',
          new: 'New Color',
          name: 'Color Name',
          hex: 'Hex Code',
          preview: 'Preview',
          add: 'Add Color'
        },
        badges: {
          title: 'Badge Management',
          new: 'New Badge',
          name: 'Badge Name',
          add: 'Add Badge'
        }
      },
      productDetail: {
        back: 'Back',
        backAdmin: 'Dashboard',
        loading: 'Loading...',
        selectOption: 'Select Option',
        variants: 'Variants',
        addVariant: 'Add Variant',
        description: 'Description',
        noDescription: 'No description available.',
        stock: 'Stock',
        code: 'Code',
        category: 'Category',
        price: 'Price',
        off: '% OFF',
        save: 'Save',
        units: 'units',
        outOfStock: 'Out',
        addToCart: 'Add to Cart',
        general: 'General',
        notFound: 'Product Not Found',
        notFoundDesc: 'The product you are looking for has been moved or is unavailable.',
        goBack: 'Go Back',
        default: 'Default',
        soldOut: 'Sold Out',
        addVariantTitle: 'Add New Variant',
        configureStock: 'Configure Stock for',
        size: 'Size / Dimensions',
        sizePlaceholder: 'e.g. XL, 42, 50ml',
        internalCode: 'Internal Code',
        inventoryStock: 'Inventory Stock',
        existingColor: 'Existing Color',
        selectColor: 'Select Color (Optional)',
        newColorName: 'Or New Color Name',
        newColorHex: 'New Color Hex Code',
        realPrice: 'Real Cost Price',
        salePrice: 'Sale Price',
        discount: 'Discount %',
        variantImages: 'Variant Images (Multi-upload)',
        deploying: 'Saving...',
        deployVariant: 'Deploy Variant',
        cancel: 'Cancel',
        delete: 'Delete',
        confirmDelete: 'Are you sure?',
        deleteVariantMsg: 'This variant will be permanently deleted and cannot be undone.'
      },
      wishlist: {
        title: 'Your Favorites',
        subtitle: 'Products you have saved for later.',
        empty: 'Your wishlist is empty',
        emptyDesc: 'Explore our collection and add items to your favorites.',
        explore: 'Start Shopping',
        removed: 'Removed from favorites',
        error: 'Operation failed',
        view: 'View Product'
      }
    }
  };

  constructor() {
    // Update document direction and lang attribute whenever currentLang changes
    effect(() => {
      const lang = this.currentLang();
      document.documentElement.lang = lang;
      document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
      localStorage.setItem('lang', lang);
    });
  }

  toggleLang() {
    this.currentLang.set(this.currentLang() === 'ar' ? 'en' : 'ar');
  }

  t(key: string): string {
    const keys = key.split('.');
    let result = this.translations[this.currentLang()];
    for (const k of keys) {
      if (result) result = result[k];
    }
    return result || key;
  }

  private getSavedLang(): 'ar' | 'en' | null {
    if (typeof window !== 'undefined') {
      return localStorage.getItem('lang') as 'ar' | 'en';
    }
    return null;
  }
}
